### ISSUE TITLE
Nada acontece

### ISSUE THREAD

**Issue by brudarko** [oiteam/oi-lab#1]
Estou tentando instalar nos pregões 83/08, com Lubuntu 64-bits, porém os usuários não são criados como também o multiterminal não é ativado. Estou fazendo algo errado?

**Comment by lbssousa** [comment]
Olá, Frank!

Com relação à criação dos usuários, eu fiz uma modificação importante (mas ainda não documentada) no commit 0597e3b. A fim de evitar quebras na geração de ISOs customizadas do Ubuntu com o oi-lab já incluso, agora o comando para a criação dos usuários deve ser executado manualmente:
```
sudo oi-lab-create-freeze-users
```

Da mesma forma, você pode remover os usuários sem precisar desistalar o pacote. Basta executar
```
sudo oi-lab-remove-freeze-users
```

Com relação ao multiterminal, se o pacote foi instalado corretamente mas as telas não sobem, você pode verificar duas coisas:

1. A placa de vídeo está funcionando corretamente? Execute o comando `lspci` e veja se aparece a placa SM501.

2. Os hubs estão ligados nas portas USB corretas? Experimente trocar as portas USB e veja se muda alguma coisa. Uma forma simples de verificar se os hubs estão nas portas certas e executar o comando `loginctl list-seats` e ver se aparece algum terminal além do padrão `seat0`.

**Comment by brudarko** [comment]
[Atualização] Consegui, erro meu. 
É normal sempre no início da sessão aparecer duas mensagens "O sistema detectou um problema no aplicativo"? Ambos Lubuntu 16.4.3 e Xubuntu 16.4.3.

**Comment by lbssousa** [comment]
Que bom que você conseguiu resolver o problema! Vou fechando por aqui.
