### ISSUE TITLE
Arquivo do userful rescue live não é mais acessível

### ISSUE THREAD

**Issue by Ronekk** [oiteam/oi-lab#2]
A URL para o download do arquivo "userful-rescue-live-20160628-i386.iso" já não é mais acessível, tornando a solução para o problema da tela listrada impossível de ser executada.

**Comment by lbssousa** [comment]
Tente baixar manualmente pelo link https://drive.google.com/u/0/uc?export=download&id=0B_0RrXAKZ1hbdnRvcGRuSFc2Nkk e copiar o arquivo para a pasta /boot.

**Comment by Ronekk** [comment]
Tentando baixar manualmente o resultado é um erro de permissão 403.

**Comment by lbssousa** [comment]
Link alternativo: https://mega.nz/file/UEcBgAhA#Srlk9sqrhe4eRLddOiLVlKoafgsZiwJ5mSZCuIk5Mhs
